//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class TheTaskDbEntities : DbContext
    {
        public TheTaskDbEntities()
            : base(@"Data Source =.\SQLEXPRESS; Initial Catalog = TheTaskDb; Integrated Security = True")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }

        public virtual DbSet<DEPT> DEPT { get; set; }
        public virtual DbSet<EMP> EMP { get; set; }
        public virtual DbSet<SALGRADE> SALGRADE { get; set; }
    }
}
