//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SALGRADE
    {
        [Key]
        public int GRADE { get; set; }
        public Nullable<int> LOSAL { get; set; }
        public Nullable<int> HISAL { get; set; }
    }
}
